#!/bin/sh

set -e

project_name=${COMPOSE_PROJECT_NAME:-routechoices}
extra_args=''

if [ "$1" = 'exec' -a $# -eq 2 ]; then
    extra_args="$* /bin/bash"
    shift 2
elif [ "$1" = 'pipcompile' ]; then
    echo "Compiling pip env..."
    docker exec -u root -i rc_django \
        uv pip compile requirements.in --upgrade --no-header --no-annotate -o requirements.txt
    exit 0
fi

export GROUPID=$(id -g) USERID=$(id -u)
exec docker compose \
    --file docker-compose.yml \
    --project-name $project_name \
    $extra_args \
    "$@"
