# Generated by Django 5.2.8 on 2025-11-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_club_is_personal_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSharingPeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                ("from_date", models.DateTimeField(auto_now_add=True)),
                ("until_date", models.DateTimeField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_devices",
                        to="core.club",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracker Sharing Period",
                "verbose_name_plural": "Trackers Sharing Periods",
                "ordering": ["-until_date"],
            },
        ),
        migrations.RemoveField(
            model_name="spotdevice",
            name="device",
        ),
        migrations.DeleteModel(
            name="SpotFeed",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="default_device",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="user",
        ),
        migrations.DeleteModel(
            name="SpotDevice",
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
    ]
