# Generated by Django 5.2.8 on 2025-12-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_remove_club_is_personal_page"),
    ]

    operations = []
