# Generated by Django 5.2.8 on 2025-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_devicesharingperiod_remove_spotdevice_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="freezed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
