# Generated by Django 5.2.8 on 2025-12-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_remove_map__corners_coordinates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="map",
            old_name="corners_coordinates",
            new_name="calibration_string_raw",
        ),
    ]
