# Generated by Django 5.2.8 on 2025-11-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_event_freezed_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="map",
            old_name="corners_coordinates",
            new_name="calibration_string",
        ),
        migrations.RemoveField(
            model_name="map",
            name="_corners_coordinates",
        ),
        migrations.AlterField(
            model_name="devicearchivereference",
            name="original",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_refs",
                to="core.device",
            ),
        ),
    ]
