# Generated by Django 5.2.8 on 2025-12-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_rename_corners_coordinates_map_calibration_string_raw"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpotFeed",
        ),
        migrations.DeleteModel(
            name="SpotDevice",
        ),
    ]
